name: agendamiento_canchas
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.2.1+1
  floor: ^1.4.2
  intl: ^0.18.1
  retrofit: ^4.0.1
  flutter_hooks: ^0.18.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ">=5.0.0 <6.0.0"
  floor_generator: 1.4.2
  build_runner: 2.3.0
  mockito: ^5.4.0
  test: ^1.22.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
